# Generated by Django 2.2.7 on 2019-11-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('lost', 'Lost'), ('approved', 'Approved'), ('shipping', 'Shipping')], max_length=50)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment.Charge')),
            ],
        ),
    ]
