# Generated by Django 2.2.7 on 2019-11-08 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='charge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Charge'),
        ),
    ]
