# Generated by Django 2.2.7 on 2019-11-08 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0003_auto_20191108_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('delivered', 'Delivered'), ('lost', 'Lost'), ('approved', 'Approved'), ('shipping', 'Shipping')], max_length=50)),
                ('date', models.DateField()),
                ('charge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.Charge')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
