# Generated by Django 2.2.7 on 2019-11-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
