# Generated by Django 2.2.7 on 2019-11-15 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20191115_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referralcode',
            old_name='discount_codes',
            new_name='discount_code',
        ),
    ]
