# Generated by Django 2.2.7 on 2019-11-15 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20191115_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referralcode',
            name='user',
        ),
        migrations.AddField(
            model_name='myuser',
            name='referral_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ReferralCode'),
        ),
        migrations.AddField(
            model_name='referralcode',
            name='expiry',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
