# Generated by Django 2.2.7 on 2019-11-15 09:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191115_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='discount_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='expiry',
            field=models.DateTimeField(default=accounts.models.three_weeks_later),
        ),
    ]
