# Generated by Django 2.2.7 on 2019-11-15 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20191115_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='referral_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='discount_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
