# Generated by Django 2.2.7 on 2019-11-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20191115_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='referral_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.ReferralCode'),
            preserve_default=False,
        ),
    ]
