# Generated by Django 2.2.7 on 2019-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20191115_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralcode',
            name='active',
            field=models.BooleanField(null=True),
        ),
    ]
