# Generated by Django 2.2.7 on 2019-11-15 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20191115_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='self_depict',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
