# Generated by Django 2.2.7 on 2019-11-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_myuser_self_depict'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
