# Generated by Django 2.2.4 on 2019-11-06 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=80)),
                ('sku', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('price', models.CharField(max_length=50)),
                ('stock_level', models.IntegerField()),
                ('sold_out', models.BooleanField()),
                ('photo', models.ImageField(null=True, upload_to='media/images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category')),
            ],
        ),
    ]
