# Generated by Django 2.2.7 on 2019-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191108_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sessions',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
